ldmd2 -O -release ../src/a.d -of ./a
rm score
./tester ./a < in/0000.txt > /dev/null 2>> score
./tester ./a < in/0001.txt > /dev/null 2>> score
./tester ./a < in/0002.txt > /dev/null 2>> score
./tester ./a < in/0003.txt > /dev/null 2>> score
./tester ./a < in/0004.txt > /dev/null 2>> score
./tester ./a < in/0005.txt > /dev/null 2>> score
./tester ./a < in/0006.txt > /dev/null 2>> score
./tester ./a < in/0007.txt > /dev/null 2>> score
./tester ./a < in/0008.txt > /dev/null 2>> score
./tester ./a < in/0009.txt > /dev/null 2>> score
./tester ./a < in/0010.txt > /dev/null 2>> score
./tester ./a < in/0011.txt > /dev/null 2>> score
./tester ./a < in/0012.txt > /dev/null 2>> score
./tester ./a < in/0013.txt > /dev/null 2>> score
./tester ./a < in/0014.txt > /dev/null 2>> score
./tester ./a < in/0015.txt > /dev/null 2>> score
./tester ./a < in/0016.txt > /dev/null 2>> score
./tester ./a < in/0017.txt > /dev/null 2>> score
./tester ./a < in/0018.txt > /dev/null 2>> score
./tester ./a < in/0019.txt > /dev/null 2>> score
./tester ./a < in/0020.txt > /dev/null 2>> score
./tester ./a < in/0021.txt > /dev/null 2>> score
./tester ./a < in/0022.txt > /dev/null 2>> score
./tester ./a < in/0023.txt > /dev/null 2>> score
./tester ./a < in/0024.txt > /dev/null 2>> score
./tester ./a < in/0025.txt > /dev/null 2>> score
./tester ./a < in/0026.txt > /dev/null 2>> score
./tester ./a < in/0027.txt > /dev/null 2>> score
./tester ./a < in/0028.txt > /dev/null 2>> score
./tester ./a < in/0029.txt > /dev/null 2>> score
./tester ./a < in/0030.txt > /dev/null 2>> score
./tester ./a < in/0031.txt > /dev/null 2>> score
./tester ./a < in/0032.txt > /dev/null 2>> score
./tester ./a < in/0033.txt > /dev/null 2>> score
./tester ./a < in/0034.txt > /dev/null 2>> score
./tester ./a < in/0035.txt > /dev/null 2>> score
./tester ./a < in/0036.txt > /dev/null 2>> score
./tester ./a < in/0037.txt > /dev/null 2>> score
./tester ./a < in/0038.txt > /dev/null 2>> score
./tester ./a < in/0039.txt > /dev/null 2>> score
./tester ./a < in/0040.txt > /dev/null 2>> score
./tester ./a < in/0041.txt > /dev/null 2>> score
./tester ./a < in/0042.txt > /dev/null 2>> score
./tester ./a < in/0043.txt > /dev/null 2>> score
./tester ./a < in/0044.txt > /dev/null 2>> score
./tester ./a < in/0045.txt > /dev/null 2>> score
./tester ./a < in/0046.txt > /dev/null 2>> score
./tester ./a < in/0047.txt > /dev/null 2>> score
./tester ./a < in/0048.txt > /dev/null 2>> score
./tester ./a < in/0049.txt > /dev/null 2>> score
./tester ./a < in/0050.txt > /dev/null 2>> score
./tester ./a < in/0051.txt > /dev/null 2>> score
./tester ./a < in/0052.txt > /dev/null 2>> score
./tester ./a < in/0053.txt > /dev/null 2>> score
./tester ./a < in/0054.txt > /dev/null 2>> score
./tester ./a < in/0055.txt > /dev/null 2>> score
./tester ./a < in/0056.txt > /dev/null 2>> score
./tester ./a < in/0057.txt > /dev/null 2>> score
./tester ./a < in/0058.txt > /dev/null 2>> score
./tester ./a < in/0059.txt > /dev/null 2>> score
./tester ./a < in/0060.txt > /dev/null 2>> score
./tester ./a < in/0061.txt > /dev/null 2>> score
./tester ./a < in/0062.txt > /dev/null 2>> score
./tester ./a < in/0063.txt > /dev/null 2>> score
./tester ./a < in/0064.txt > /dev/null 2>> score
./tester ./a < in/0065.txt > /dev/null 2>> score
./tester ./a < in/0066.txt > /dev/null 2>> score
./tester ./a < in/0067.txt > /dev/null 2>> score
./tester ./a < in/0068.txt > /dev/null 2>> score
./tester ./a < in/0069.txt > /dev/null 2>> score
./tester ./a < in/0070.txt > /dev/null 2>> score
./tester ./a < in/0071.txt > /dev/null 2>> score
./tester ./a < in/0072.txt > /dev/null 2>> score
./tester ./a < in/0073.txt > /dev/null 2>> score
./tester ./a < in/0074.txt > /dev/null 2>> score
./tester ./a < in/0075.txt > /dev/null 2>> score
./tester ./a < in/0076.txt > /dev/null 2>> score
./tester ./a < in/0077.txt > /dev/null 2>> score
./tester ./a < in/0078.txt > /dev/null 2>> score
./tester ./a < in/0079.txt > /dev/null 2>> score
./tester ./a < in/0080.txt > /dev/null 2>> score
./tester ./a < in/0081.txt > /dev/null 2>> score
./tester ./a < in/0082.txt > /dev/null 2>> score
./tester ./a < in/0083.txt > /dev/null 2>> score
./tester ./a < in/0084.txt > /dev/null 2>> score
./tester ./a < in/0085.txt > /dev/null 2>> score
./tester ./a < in/0086.txt > /dev/null 2>> score
./tester ./a < in/0087.txt > /dev/null 2>> score
./tester ./a < in/0088.txt > /dev/null 2>> score
./tester ./a < in/0089.txt > /dev/null 2>> score
./tester ./a < in/0090.txt > /dev/null 2>> score
./tester ./a < in/0091.txt > /dev/null 2>> score
./tester ./a < in/0092.txt > /dev/null 2>> score
./tester ./a < in/0093.txt > /dev/null 2>> score
./tester ./a < in/0094.txt > /dev/null 2>> score
./tester ./a < in/0095.txt > /dev/null 2>> score
./tester ./a < in/0096.txt > /dev/null 2>> score
./tester ./a < in/0097.txt > /dev/null 2>> score
./tester ./a < in/0098.txt > /dev/null 2>> score
./tester ./a < in/0099.txt > /dev/null 2>> score

SCORE=`cat score | awk '{sum+=$4} END {printf "%.2f\n", sum / 100}'`
echo $SCORE

DATE=`date "+%Y/%m/%d %H:%M:%S"`
echo -e "${DATE}\t${SCORE}" >> score_history
